#!/usr/bin/env ruby

require 'open3'
require 'uri'
require 'net/http'
require_relative '../lib/fgi'

# extract core logic from here into the gem bin
module Fgi
  class Command
    def initialize(content)
      # convert title into a string we can use in a curl request
      content = content.join(' ')
      case
      when content.empty?
        Fgi::Helper.run
      when content.match(/--help/)
        Fgi::Helper.run
      when content.match(/--config/)
        Fgi::Configurator.run
      when content.match(/--token/)
        Fgi::Configurator.validate_and_save_gitlab_token(content.strip.split(' ').last)
      else
        create_issue(content)
      end
    end

    # Get the issue's description and initiate its creation
    # @param title [String] the issue's title
    def create_issue(title)
      puts "\nWrite your issue description right bellow (save and quit with CTRL+D) :"
      puts "---------------------------------------------------------------------\n\n"
      begin
        description = STDIN.read
      rescue Interrupt => int
        puts %q[Why did you killed me ? :'(]
        exit!
      end
      Fgi::Executor.new.process_data(title, description)
    end
  end
end

Fgi::Command.new(ARGV)
