#!/usr/bin/env ruby

require 'open3'
require 'uri'
require 'net/http'
require_relative '../lib/fgi'

# extract core logic from here into the gem bin
module Fgi
  class Command
    def initialize(content)
      # convert title into a string we can use in a curl request
      content = content.join(' ')
      case
      when content.empty?
        Fgi::Helper.run
      when content.match(/--help/)
        Fgi::Helper.run
      when content.match(/--config/)
        Fgi::Configurator.run
      when content.match(/--token/)
        Fgi::Configurator.validate_and_save_gitlab_token(content.strip.split(' ').last)
      else
        title = content
        description = []
        success = system('vim temp.txt')
        if success
          File.open('temp.txt', 'r') do |f|
            f.each_line do |line|
              description << line
            end
          end
          # convert the description of the issue into a string we can use in a curl request
          description = description.join
        end
        Fgi::Executor.new.process_data(title, description)
      end
    end
  end
end

Fgi::Command.new(ARGV)
